name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *' 
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 23f2000296@ds.study.iitm.ac.in 
        run: |
          echo "GitHub Action ran at $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit on $(date)"
          git push
